In [3]:
import numpy as np
a = np.array([1,2,3,4])
a+1

array([2, 3, 4, 5])

In [4]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [5]:
#All arithmetic operations are element wise

SyntaxError: invalid syntax (<ipython-input-5-fa088a009e87>, line 1)

In [9]:
b = np.ones(4) + 1
b
a - b

array([-1.,  0.,  1.,  2.])

In [10]:
a * b

array([2., 4., 6., 8.])

In [15]:
# Matrix Multiplication

c = np.diag([1,2,3,4])

print(c * c)
print("***********")
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
***********
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [17]:
#Comparisons

a = np.array([1 ,2, 3, 4])
b = np.array([3, 2, 1, 4])
a == b

array([False,  True, False,  True])

In [18]:
a > b

array([False, False,  True, False])

In [22]:
#Array-wise comparison

a = np.array([1 ,2, 3, 4])
b = np.array([3, 2, 1, 4])
c = np.array([1, 2, 3, 4])

np.array_equal(a,b)


False

In [23]:
np.array_equal(a, c)


True

In [24]:
# Logical Operations
a = np.array([1, 0, 1, 1])
b = np.array([1, 1, 0, 1])

np.logical_and(a, b)

array([ True, False, False,  True])

In [25]:
np.logical_or(a, b)

array([ True,  True,  True,  True])

In [26]:
#Transcendental Functions

In [27]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [29]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [30]:
np.log(a)

<ipython-input-30-89b6b8e53c58>:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [32]:
np.exp(a) # e^x

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [33]:
#Shape Mismatch
a = np.arange(4)
a + np.array([1, 2])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [34]:
#Basic Reduction
#Computing Sums


In [35]:
x = np.array([1, 2, 3, 4])
np.sum(x)

10

In [36]:
x = np.array([[1, 1], [2, 2]])
x

array([[1, 1],
       [2, 2]])

In [37]:
x.sum(axis=0) # Column first dimension

array([3, 3])

In [39]:
x.sum(axis=1)

array([2, 4])

In [40]:
#Other reductions

In [41]:
x = np.array([1, 2, 3, 4])
x.min()

1

In [42]:
x.max()

4

In [43]:
x.argmin() #index of minimum element

0

In [44]:
x.argmax() #index of maximum element

3

In [45]:
#Logical Operations

In [46]:
np.all([True, True, False])

False

In [47]:
np.all([True, True, True])

True

In [48]:
np.any([True, True, False])

True

In [49]:
a = np.zeros((50, 50))
np.any(a != 0)

False

In [50]:
np.all( a == a)

True

In [53]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])
((a <= b) & (b <= c)).all()

True

In [54]:
#Statistics

In [55]:
x = np.array([1, 2, 3, 1])
y = np.array([[1, 2, 3], [5, 6, 1]])
x.mean()

1.75

In [56]:
np.median(x)

1.5

In [57]:
#Axis = 0 --> Column
#Axis = 1 --> Rows


In [58]:
np.median(y, axis=1) #Last axis

array([2., 5.])

In [59]:
x.std()

0.82915619758885

In [60]:
# load data
data = np.loadtxt('populations.txt')
populations.std(axis=0)
np.argmax(populations, axis=1)

OSError: populations.txt not found.

In [61]:
#Broadcasting

In [6]:
import numpy as np
a = np.tile(np.arange(0, 40, 10), (3, 1))
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]


In [7]:
a = a.T
print(a)

[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [8]:
b = np.array([0, 1, 2])
b

array([0, 1, 2])

In [9]:
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [10]:
b

array([0, 1, 2])

In [11]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [12]:
a = np.arange(0, 40, 10)
a


array([ 0, 10, 20, 30])

In [13]:
a = a[:, np.newaxis] # Adds a new axis -> 2D Array
a.shape

(4, 1)

In [14]:
a

array([[ 0],
       [10],
       [20],
       [30]])

In [15]:
# Array Shape Manipulation

In [16]:
#Flatterning

In [18]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
a.ravel() # Returned a continous flattened array.

array([1, 2, 3, 4, 5, 6])

In [20]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [21]:
a.T.ravel()


array([1, 4, 2, 5, 3, 6])

In [22]:
b = a.ravel()
b

array([1, 2, 3, 4, 5, 6])

In [23]:
b = b.reshape((2, 3))
b

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
b[0, 0] = 100
a

array([[100,   2,   3],
       [  4,   5,   6]])

In [26]:
z = np.array([1, 2, 3])
z

array([1, 2, 3])

In [27]:
a = np.arange(4*3*2).reshape(4, 3, 2)
a.shape

(4, 3, 2)

In [28]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [29]:
a[0, 2, 1]

5

In [30]:
#Resizing

In [34]:
a = np.arange(4)
a
a.resize((8,))
a

array([0, 1, 2, 3, 0, 0, 0, 0])

In [35]:
#Sorting

In [36]:
a = np.array([[5, 4, 6],[2, 3, 2]])
b = np.sort(a, axis=1)
b

array([[4, 5, 6],
       [2, 2, 3]])

In [37]:
#in-place sort
a.sort(axis=1)
a

array([[4, 5, 6],
       [2, 2, 3]])

In [39]:
#Fancy indexing
a = np.array([4, 3, 1, 2])
j = np.argsort(a) # Sort the index
j

array([2, 3, 1, 0], dtype=int64)

In [40]:
a[j]

array([1, 2, 3, 4])