In [3]:
import numpy as np
a = np.array([0, 1, 2, 3])
print(a)

[0 1 2 3]


In [4]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [5]:
#Python list
L=  range(1000)
%timeit [i**2 for i in L]

240 µs ± 9.67 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [6]:
a = np.arange(1000)
%timeit a**2

1.49 µs ± 29.8 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [7]:
# 1-D Array

a = np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [8]:
a.ndim

1

In [9]:
a.shape

(4,)

In [10]:
len(a)

4

In [11]:
# 2-D , 3-D Array
b = np.array([[0, 1, 2], [3, 4, 5]])

In [12]:
b

array([[0, 1, 2],
       [3, 4, 5]])

In [13]:
b.ndim

2

In [14]:
b.shape

(2, 3)

In [15]:
len(b)

2

In [16]:
c = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [17]:
c.ndim

3

In [18]:
c.shape

(2, 2, 2)

In [19]:
# 1-D array is Vector
# 2-D array is called Matrix
# N-D array is called Tensor

In [20]:
b = np.arange(1, 10, 2) # Start , End, Step
b

array([1, 3, 5, 7, 9])

In [23]:
#Using Linspace

a = np.linspace(0, 1, 6) # Start, End , Number of Points
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [24]:
# Common Arrays

a= np.ones((3, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
b = np.zeros((3,3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [28]:
#Identity Matrix where 1 is in the diagnol of the matrix
c=np.eye(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
d = np.eye(3, 2)
d

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [30]:
#Create array using diag function

a = np.diag([1,2,3,4])
a
            

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [31]:
np.diag(a)

array([1, 2, 3, 4])

In [32]:
#Create array using random

a = np.random.rand(4) #Uniform distributed random numbers
a

array([0.95453122, 0.01078205, 0.9156466 , 0.18518888])

In [33]:
#Basic Data Types

In [34]:
a = np.arange(10)
a.dtype

dtype('int32')

In [35]:
# If you want float
a = np.arange(10, dtype='float64')
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [36]:
d = np.array([1+2j, 2+4j])
print(d.dtype)

complex128


In [39]:
b = np.array([True, True, False, True]) #Boolean Datatype Array
print(b.dtype)

bool


In [42]:
c = np.array(['Ram', 'Shyam', 'Mohan']) #String Numpy Array
c.dtype

dtype('<U5')

In [43]:
#Indesxing and Slicing
a = np.arange(10)

print(a[5]) 

5


In [44]:
# For multidimension arrays, indexes are tuples of integers

a = np.diag([1,2,3])
print(a[2,2])

3


In [45]:
a[2, 1] = 5 # Assigning value

a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

In [46]:
#Slicing

In [47]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
a[1:8:2] # Start : End: Step

array([1, 3, 5, 7])

In [49]:
a = np.arange(10)
a[5:] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [51]:
b = np.arange(5)
b

array([0, 1, 2, 3, 4])

In [52]:
a[5:] = b[::-1] # Assigning
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [53]:
# Copies And Views

In [54]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
b = a[::2]
b # b points to same memory location  using view

array([0, 2, 4, 6, 8])

In [57]:
np.shares_memory(a, b)

True

In [58]:
b[0] = 10
b

array([10,  2,  4,  6,  8])

In [59]:
a

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [60]:
# if we slice and assign then it changes value in both the array

In [61]:
a = np.arange(10)
a


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
c = a[::2].copy()
c

array([0, 2, 4, 6, 8])

In [63]:
c[0]=10
c

array([10,  2,  4,  6,  8])

In [64]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
np.shares_memory(a,c)

False

In [66]:
# Fancy Indexing

In [67]:
a = np.random.randint(0, 20, 15)
a

array([ 2, 18, 19, 16, 18,  7,  5, 15, 10,  8,  7,  5,  6,  1, 16])

In [68]:
mask = (a % 2 == 0)

In [69]:
extract_from_a = a[mask]
extract_from_a

array([ 2, 18, 16, 18, 10,  8,  6, 16])

In [70]:
a[mask] = -1
a

array([-1, -1, 19, -1, -1,  7,  5, 15, -1, -1,  7,  5, -1,  1, -1])

In [71]:
a = np.arange(0, 100, 10)

In [72]:
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [73]:
a[[2, 3, 2, 4, 2]]

array([20, 30, 20, 40, 20])

In [74]:
# New Values can be assigned
a[[9, 7]] = -200

a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])